def exit_with_error(msg):
    exit(msg)


def exit_suc(msg):
    print(msg)
    exit(1)
